### ISSUE TITLE
Npcs being added multiple times to data/mail

### ISSUE THREAD

**Issue by janavarro95** [janavarro95/Stardew_Valley_Mods#82]
Seems like sometimes a npc might be added twice due to how other mods implement their npcs. Will need to add a safety check for this.

[Happy Birthday] Mod crashed when editing asset 'Data/mail', which may cause errors in-game. Error details:
ArgumentException: An item with the same key has already been added. Key: Sophia
key: 'Sophia'
   at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[StardewValley.GameData.SpecialOrderData, StardewValley.GameData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add_Patch1(Dictionary`2 this, String key, SpecialOrderData value)
   at Omegasis.HappyBirthday.Framework.Constants.MailKeys.GetAllBelatedBirthdayMailKeys() in C:\Users\Joshua Navarro\Desktop\Stardew_Valley_Mods\GeneralMods\HappyBirthday\Framework\Constants\MailKeys.cs:line 67
   at Omegasis.HappyBirthday.Framework.Utilities.MailUtilities.EditMailAsset(IAssetData asset) in C:\Users\Joshua Navarro\Desktop\Stardew_Valley_Mods\GeneralMods\HappyBirthday\Framework\Utilities\MailUtilities.cs:line 27
   at StardewModdingAPI.Framework.ContentManagers.GameContentManager.ApplyEditors[T](IAssetInfo info, IAssetData asset) in SMAPI\Framework\ContentManagers\GameContentManager.cs:line 360

**Comment by janavarro95** [comment]
Fixed in Happy Birthday 3.0.6
